configuration:
  builder_filter:
    - amd64-debian-12-deb-autobake-migration
    - amd64-rhel-9-rpm-autobake-migration
  branches:
    - 10.6
    - 10.11
    - 11.4
    - 11.8
    - 12.1
    - 12.2
    - 12.3
    - main